version: "3.4"
services:
  web:
    image: daocloud.io/library/nginx:latest
    privileged: true
    volumes:
      - ./dist:/usr/share/nginx/html
    #ports: 
    #  - 8000:80

networks:
  default:
    external:
      name: sandbox_network
